PreCommit:
  Rubocop:
    enabled: true
    on_warn: fail

  CssLint:
    enabled: false

  ScssLint:
    enabled: true
    on_warn: fail
    include: 'app/assets/stylesheets/**/*.scss'

  Reek:
    enabled: false

  HamlLint:
    enabled: true
    on_warn: fail
    include: 'app/views/**/*.haml'

  HardTabs:
    enabled: true
    on_warn: fail
    exclude:
      - 'vendor/**/*'
      - 'erb/**/*'

  TrailingWhitespace:
    enabled: true
    on_warn: fail
    exclude:
      - 'vendor/**/*'
      - 'erb/**/*'

  TravisLint:
    enabled: false
