AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/spec_helper.rb'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Style/FileName:
  Exclude:
    - 'Gemfile'
