language: ruby
rvm:
  - 2.3.1

sudo: false

bundler_args: --without production development
before_script:
  - bin/rails db:migrate RAILS_ENV=test
  - export TZ=Canada/Pacific

script:
  - bundle exec cucumber
  - bundle exec rspec spec

after_script:
  - CODECLIMATE_REPO_TOKEN=73bdd89da2ab3fecea83dbd973bbb186f3926f00d1d2bba8a73176d6e8561ba4 bundle exec codeclimate-test-reporter
