language: ruby
rvm:
  - 2.2.0

sudo: false

addons:
  code_climate:
    repo_token: 73bdd89da2ab3fecea83dbd973bbb186f3926f00d1d2bba8a73176d6e8561ba4

bundler_args: --without production
before_script:
  - export TZ=Canada/Pacific

script:
  - bundle exec cucumber
  - bundle exec rspec spec
