language: ruby
rvm:
  - 2.2.0

addons:
  code_climate:
    repo_token: 73bdd89da2ab3fecea83dbd973bbb186f3926f00d1d2bba8a73176d6e8561ba4

bundler_args: --without production
before_script:
  - echo 'Canada/Pacific' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script:
  - bundle exec cucumber -f progress
  - bundle exec rspec spec
