language: ruby
rvm:
  - 2.3.1

sudo: false

bundler_args: --without production development
before_script:
  - bin/rails db:migrate RAILS_ENV=test
  - export TZ=Canada/Pacific
  - npm install -g bower
  - bower install

script:
  - bundle exec cucumber
  - bundle exec rspec spec

after_script:
  - bundle exec codeclimate-test-reporter
